version: '3'
services:

  app:
    build:
      dockerfile: ./Dockerfile 
      context: .
    volumes:
      - ./flask_app:/app
    environment:
      - FLASK_APP=map.py
      - FLASK_ENV=development
    ports:
      - 5000:5000 
    command: flask run --host=0.0.0.0

  mongo_db:
    image: mongo
